configuration: Release

matrix:
    fast_finish: true

build_script:
    - Make.bat

test_script:
    - timeout /t 30
    - Make.bat test

notifications:
    email: true
    irc: "irc.freenode.org#virgo"

services:
    - mssql2008r2sp2
    - mssql2012sp1
