#
#  Copyright 2011 Rackspace
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#


Import('env')

from os.path import dirname

targets = {}

sources = Split("""
virgo_error.c
virgo_init.c
virgo_lua.c
virgo_lua_loader.c
virgo_lua_debugger.c
""")
# virgo_lua_debugger.c

libvirgo = None

lenv = env.Clone()
lenv.AppendUnique(CPPPATH=['#/include/private'])
# Currently really hard to be pedantic and Werror, due to OpenSSL's use of long long :(
#lenv.AppendUnique(CPPFLAGS=['-Werror'])

targets['static'] = lenv.StaticLibrary('libvirgo', sources)

Return('targets')
