/*This file is generated by gyp_utils.py */
#include <string.h>
#include "virgo_exports.h"

const void *virgo_ugly_hack = NULL;
extern const char *luaJIT_BC_virgo_debugger[];
extern const char *luaJIT_BC_virgo_init[];
extern const char *luaJIT_BC_virgo_utils[];

const void *virgo__suck_in_symbols(void)
{
  virgo_ugly_hack = (const char*)

  (size_t)(const char *)luaJIT_BC_virgo_debugger +
  (size_t)(const char *)luaJIT_BC_virgo_init +
  (size_t)(const char *)luaJIT_BC_virgo_utils;

  return virgo_ugly_hack;
}
