#!/bin/sh
#
# Startup script for $SHORT_DESCRIPTION
#
# chkconfig: 345 85 15     - start or stop process definition within the boot process
# description: $SHORT_DESCRIPTION
# processname: $PKG_NAME
# pidfile: /var/run/$PKG_NAME.pid

NAME=$PKG_NAME
DAEMON=/usr/bin/$PKG_NAME
PIDFILE=/var/run/$PKG_NAME.pid
LOG=/var/log/$PKG_NAME.log

# Source function library.      This creates the operating environment for the process to be started
. /etc/init.d/functions

case "$1" in
  start)
        echo -n "Starting $DAEMON: "
        daemon $DAEMON -D -p $PIDFILE -l $LOG --production --restart-sysv-on-upgrade
        echo
        touch /var/lock/subsys/process-name
        ;;
  stop)
        echo -n "Shutting down $DAEMON: "
        killproc $DAEMON
        echo
        rm -f $PIDFILE
        ;;
  status)
        status $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  reload)
        echo -n "Reloading $DAEMON: "
        killproc $DAEMON -HUP
        echo
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
