#!/usr/bin/env python
import glob
import os
import platform
import shutil
import subprocess
import sys

from pkgtype import pkg_type, pkg_dir
from optparse import OptionParser

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, 'out')

def create_rpm(src, dest):
    if os.path.isdir(dest):
        print "assuming %s is already a repo" % dest
    elif os.mkdir(dest):
        print "created %s" % dest

    # Copy RPMs into the target repo
    rpm_dirs = ["SRPMS", "RPMS/*"]
    for d in rpm_dirs:
        for f in glob.glob(os.path.join(src, d, '*.rpm')):
            shutil.copy(f, dest)

    if subprocess.call("createrepo %s" % dest, shell=True) == 0:
        print("createrepo OK")
        return 0
    else:
        print("createrepo FAILED")
        return 1

def create_deb(src, dest, dist):
    conf = os.path.join(dest, 'conf')
    distributions = """Codename: cloudmonitoring
Components: main
Architectures: i386 amd64 source
Origin: Rackspace
Description: Rackspace Cloud Monitoring Agent for %s %s
SignWith: D05AB914
""" % (dist[0], dist[1])

    if not os.path.isdir(dest):
        os.mkdir(dest)
    if not os.path.isdir(conf):
        os.mkdir(conf)

    f = open(os.path.join(conf, 'distributions'), 'w')
    f.write(distributions)
    f.close()

    reprepro = "reprepro -b %s includedeb cloudmonitoring %s"
    for deb in glob.glob(os.path.join(src, '*.deb')):
        if subprocess.call(reprepro % (dest, deb), shell=True) == 0:
            print("includedeb %s OK", deb)
        else:
            print("includedeb %s FAILED", deb)
            return 1

    return 0

if __name__ == "__main__":
    pkg = pkg_type()

    usage = "usage: %prog destination"
    parser = OptionParser(usage=usage)
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.print_usage()
        sys.exit(1)

    dest = args[0]

    dist = platform.dist()
    dest = os.path.join(dest, pkg_dir())

    if pkg == 'rpm':
        src = os.path.join(out, 'rpmbuild')
        sys.exit(create_rpm(src, dest))
    elif pkg == 'deb':
        src = os.path.join(out, 'debbuild')
        sys.exit(create_deb(src, dest, dist))
